### PR TITLE
PLEASE REVIEW - Dt48 one combined html file r1

### PR DESCRIPTION
**Pull request by coreysals**
Issues:
https://alliancels.myjetbrains.com/youtrack/issue/DT-48
https://alliancels.myjetbrains.com/youtrack/issue/TIT-84

Jeremy already reviewed and approved my [initial branch/PR](https://github.com/alliancels/documentation-gradle-plugins/pull/2) so this PR is mostly to get @benhammen's feedback. 

Let me know if you have any questions

Thanks!

In order to test this on the documentation-gradle-plugins example project:
-Checkout this branch
-In cmd.exe go to WorkingDirectory/documentation-gradle-plugins/example
-Run "gradlew --include-build .. aA --rerun-tasks" command
-Run "gradlew --include-build .. combineAll" command
-Check to see that combined documents were generated in the WorkingDirectory/documentation-gradle-plugins/example/documentation/All directory.
-Check to see that combined documents were added to bottom of the navigation pane in navigation.html.
-Combined docs can be easily printed to .pdf from Chrome (or your browser of choice)

In order to test this on Midas/Titan documentation:
-Go to gradle.build file for Midas/Titan documentation
-Change the maven-repo path from "release" to "test_DT48_CombineDocs_r1"
-In cmd.exe go to WorkingDirectory/Titan
-Run "gradlew --refresh-dependencies" command
-Run "gradlew Docs:aA --rerun-tasks" command
-Run "gradlew Docs:combineAll" command

### CODE REVIEW

**Review by benhammen — COMMENTED** [review]
Is section nesting planned to be added later?  It should really be Section 2, and then Section 2.1 in this case:

>Section 2 - DeveloperGuide\ToolInstallation\section.html
Tool Installation
>Section 3 - DeveloperGuide\ToolInstallation\Linux\section.html
Linux

**Comment by coreysals** [comment]
> Is section nesting planned to be added later? It should really be Section 2, and then Section 2.1 in this case:
> 
> > Section 2 - DeveloperGuide\ToolInstallation\section.html
> > Tool Installation
> > Section 3 - DeveloperGuide\ToolInstallation\Linux\section.html
> > Linux

Sounds good to me. I (obviously) only implemented simple section/page numbering. I will implement this idea.

**Comment by coreysals** [comment]
Added nested section numbering scheme.
image

I also updated the test_DT48_CombineDocs_r1 maven-repo external project test branch to include changes.

Jeremy and I were discussing (following his suggestion) how it might look cleaner putting the section number in front of the title and removing the html path at the top of the section entirely for the combined docs. This of course can be done but I left it mostly as is for now.

**Comment by coreysals** [comment]
Oh darn I found a bug (obvious one at that...my bad) when testing on Titan Docs. Will fix...

**Comment by coreysals** [comment]
Should be fixed now. 

I (again) updated the test_DT48_CombineDocs_r1 maven-repo external project test branch to include bug fix.

**Review by jdoutine — APPROVED** [review]
Updates seem good and worked when building Titan Docs

**Review by benhammen — APPROVED** [review]

**Comment by coreysals** [comment]
Thanks for reviewing!

**Pull request merged**
